#!/usr/bin/env python3
"""Generate playbook/MANIFEST.md from each page's YAML frontmatter.

Source of truth = the frontmatter block at the top of every
playbook/<scope>/<tool>.md page. This script collects those blocks into a
single index table that the tooling-sync skill reads first to decide which
pages are relevant to a given repo.

Stdlib only. Run: python3 scripts/build_manifest.py
"""

from __future__ import annotations

import contextlib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
PLAYBOOK = ROOT / "playbook"
MANIFEST = PLAYBOOK / "MANIFEST.md"

SCOPE_ORDER = ["universal", "python", "node", "k8s", "monorepo"]

ROW_TEMPLATE = (
    "| `{tool}` | {tier} | {summary} | {targets} | "
    "{detect} | {platform} | [{path}]({path}) |"
)


def parse_frontmatter(text: str) -> dict[str, Any] | None:
    """Parse a leading `---` YAML-ish frontmatter block.

    Handles scalars (quoted or bare) and inline JSON lists (`["a", "b"]`),
    which is all our schema uses — no PyYAML dependency.
    """
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    data: dict[str, Any] = {}
    for raw in text[3:end].splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.strip()
        if val.startswith(("[", "{")):
            with contextlib.suppress(json.JSONDecodeError):
                val = json.loads(val)
        else:
            val = val.strip('"').strip("'")
        data[key] = val
    return data


def fmt_list(val: object) -> str:
    if isinstance(val, list):
        return ", ".join(f"`{x}`" for x in val) if val else "—"
    return f"`{val}`" if val else "—"


def _as_list(val: object) -> list[str]:
    if isinstance(val, list):
        return [str(x) for x in val]
    return [str(val)] if val else []


def combined_detect(p: dict[str, Any]) -> list[str]:
    """Path globs (`detect`) plus content regexes (`detect_content`, shown as
    `content:<re>`) — both signal relevance, so both appear in the Detect column."""
    return _as_list(p.get("detect")) + [
        f"content:{c}" for c in _as_list(p.get("detect_content"))
    ]


def main() -> int:
    pages: list[dict[str, Any]] = []
    for md in sorted(PLAYBOOK.rglob("*.md")):
        if md.name in {"README.md", "MANIFEST.md"}:
            continue
        fm = parse_frontmatter(md.read_text())
        if not fm or "tool" not in fm:
            print(f"warn: no frontmatter in {md.relative_to(ROOT)}", file=sys.stderr)
            continue
        fm["_path"] = md.relative_to(PLAYBOOK).as_posix()
        pages.append(fm)

    out = [
        "<!-- GENERATED by scripts/build_manifest.py from page frontmatter. "
        "Do not edit by hand. -->",
        "",
        "# Playbook Manifest",
        "",
        "Machine-readable index of every playbook page. Source of truth = each "
        "page's YAML frontmatter; regenerate with `python3 scripts/build_manifest.py`.",
        "",
        "- **tier** — `baseline` (most repos should adopt) vs `optional` "
        "(context-specific pattern).",
        "- **targets** — files/dirs in a consumer repo this page governs "
        "(what to compare / where to apply).",
        "- **detect** — path globs, plus `content:<re>` regexes matched against "
        "YAML bodies; if any matches the page is relevant "
        "(— = always relevant for its scope/platform).",
        "- **platform** — restricts relevance to `github` or `gitlab` "
        "(any = no restriction).",
        "",
    ]

    for scope in SCOPE_ORDER:
        group = sorted(
            (p for p in pages if p.get("scope") == scope),
            key=lambda p: p.get("tool", ""),
        )
        if not group:
            continue
        out += [
            f"## {scope}",
            "",
            "| Tool | Tier | Summary | Targets | Detect | Platform | Page |",
            "|---|---|---|---|---|---|---|",
        ]
        for p in group:
            out.append(
                ROW_TEMPLATE.format(
                    tool=p.get("tool", ""),
                    tier=p.get("tier", "") or "—",
                    summary=p.get("summary", "") or "",
                    targets=fmt_list(p.get("targets")),
                    detect=fmt_list(combined_detect(p)),
                    platform=f"`{p['platform']}`" if p.get("platform") else "any",
                    path=p["_path"],
                )
            )
        out.append("")

    MANIFEST.write_text("\n".join(out).rstrip() + "\n")
    print(f"wrote {MANIFEST.relative_to(ROOT)} ({len(pages)} pages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
